name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env:
  QT_VERSION: 5.12.9
jobs:
  build_win_mac:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Build on ${{matrix.os }}

    steps:
      - name: this is test job
        run: |
          echo "this is test job"
          echo $QT_VERSION

  build_linux:
    strategy:
      matrix:
        container: ['shahbaz/ubuntu:18.04', 'shahbaz/centos:7']
    runs-on: ubuntu-latest
    name: Build on ${{matrix.container }}
    container: ${{ matrix.container }}

    steps:
      - name: this is test job
        if:  matrix.container == 'shahbaz/centos:7'
        run: |
          echo "this is test job"
          echo $QT_VERSION
          gcc --version
          g++ --version
          cat /etc/bashrc
          source /opt/rh/devtoolset-9/enable
          gcc --version
          g++ --version
          bash -c "gcc --version"
          bash -c "g++ --version"